# Generated by Django 4.1.5 on 2023-11-12 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_gap_gap'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penilaian_kriteria', models.IntegerField()),
                ('penilaian_alternatif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.alternatif')),
            ],
        ),
    ]
