# Generated by Django 4.1.5 on 2023-11-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_penilaian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penilaian',
            name='penilaian_kriteria',
        ),
        migrations.AddField(
            model_name='penilaian',
            name='penilaian_kriteria1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='penilaian_kriteria2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='penilaian_kriteria3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='penilaian_kriteria4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='penilaian',
            name='penilaian_kriteria5',
            field=models.IntegerField(default=0),
        ),
    ]
